apiVersion: v1
kind: Service
metadata:
  name: odh-tec
  labels:
    app: odh-tec
spec:
  selector:
    app: odh-tec
  ports:
    - port: 80
      targetPort: 8888
      protocol: TCP
      name: http
