apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finsight-root-application
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'https://github.com/finsignt-demojam/mono-repo'
    targetRevision: main
    path: clusters/rosa
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
