apiVersion: v1
kind: Service
metadata:
  name: shakeout-app-service
  labels:
    app: shakeout-app
spec:
  selector:
    app: shakeout-app
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000