apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  namespace: finsight-agent
  annotations:
    eventing.knative.dev/broker.class: Kafka
    argocd.argoproj.io/sync-wave: "40"
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-config
    namespace: knative-eventing
