apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: finsight-project
  namespace: openshift-gitops
spec:
  sourceRepos:
  - https://github.com/finsignt-demojam/mono-repo\
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'